apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dotnet
  labels:
    app: hello-world-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-dotnet
  template:
    metadata:
      labels:
        app: hello-world-dotnet
    spec:
      containers:
        - name: hello-world-dotnet
          image: 920373030046.dkr.ecr.us-east-1.amazonaws.com/dotnethelloworld:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
