apiVersion: v1
kind: Service
metadata:
  name: hello-world-dotnet
  labels:
    app: hello-world-dotnet
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-world-dotnet
