apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-dotnet
  namespace: cp-dotnet
spec:
  project: default
  source:
    repoURL: 'https://github.com/alhaj1986/dotnetwebapphelloworld.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
