apiVersion: v1
kind: Service
metadata:
  name: my-app-dotnet-service
  namespace: cp-dotnet
spec:
  selector:
    app: my-app-dotnet
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
